"""init

Revision ID: c98909fe28ea
Revises: 
Create Date: 2025-11-27 12:24:38.446296+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c98909fe28ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Internal filename'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='Original filename'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='Storage path'),
    sa.Column('size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME type'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='Owner user ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='File description'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='Public access'),
    sa.Column('download_count', sa.Integer(), nullable=False, comment='Download count'),
    sa.Column('shared_with', postgresql.ARRAY(sa.UUID()), nullable=False, comment='Shared with user IDs'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_is_deleted'), 'files', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_files_is_public'), 'files', ['is_public'], unique=False)
    op.create_index(op.f('ix_files_mime_type'), 'files', ['mime_type'], unique=False)
    op.create_index(op.f('ix_files_name'), 'files', ['name'], unique=True)
    op.create_index(op.f('ix_files_owner_id'), 'files', ['owner_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Unique username'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='User first name'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='User last name'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether user is active'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_files_owner_id'), table_name='files')
    op.drop_index(op.f('ix_files_name'), table_name='files')
    op.drop_index(op.f('ix_files_mime_type'), table_name='files')
    op.drop_index(op.f('ix_files_is_public'), table_name='files')
    op.drop_index(op.f('ix_files_is_deleted'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###